LINUX_SRC=/lib/modules/$(shell uname -r)/build

export CONFIG_MTK_COMBO_PLATFORM=x86
export MTK_COMBO_CHIP=MT6632

PWD=$(shell pwd)
DRIVER_DIR=$(PWD)/drv_wlan/$(MTK_COMBO_CHIP)/wlan
#COMMON_DIR=$(PWD)/common

export CONFIG_MTK_WIFI_ONLY=m
export CONFIG_MTK_COMBO=m
export CONFIG_MTK_COMBO_WIFI=m
export CONFIG_MTK_COMBO_COMM=m
export CONFIG_MTK_COMBO_COMM_UART=m
export CONFIG_MTK_COMBO_COMM_SDIO=m
export CONFIG_MT_WIFI_CHRDEV=m

# pcie | sdio | usb
ifeq ($(hif),)
    hif=usb
endif

export CONFIG_MTK_COMBO_WIFI_HIF=$(hif)

export CONFIG_MTK_COMBO_PLAT_PATH=x86
all: driver common

driver: common
	+cd $(DRIVER_DIR) && make -C $(LINUX_SRC) M=$(DRIVER_DIR) modules
	@cat $(DRIVER_DIR)/Module.symvers >> $(LINUX_SRC)/Module.symvers

#common:
#	+cd $(COMMON_DIR) && make -C $(LINUX_SRC) M=$(COMMON_DIR) modules
#	@cat $(COMMON_DIR)/Module.symvers >> $(LINUX_SRC)/Module.symvers

clean: symvers_clean

symvers_clean: driver_clean common_clean
	@cp $(LINUX_SRC)/Module.symvers.original $(LINUX_SRC)/Module.symvers

driver_clean:
	cd $(DRIVER_DIR) && make -C $(LINUX_SRC) M=$(DRIVER_DIR) clean

#common_clean:
#	cd $(COMMON_DIR) && make -C $(LINUX_SRC) M=$(COMMON_DIR) clean

.PHONY: all clean common common_clean driver driver_clean
